### ISSUE TITLE
Markdown Commands not rendered

### ISSUE THREAD

**Issue by Paula-Kli** [fsr-de/myHPI#117]
![image](https://user-images.githubusercontent.com/49535291/177406263-4a77bc11-575f-4185-ab2d-bf68c229a375.png)

**Comment by jeriox** [comment]
closed in #116

**Comment by frcroth** [comment]
Broken again

**Comment by jeriox** [comment]
nope, this is an issue with the button that creates the commands. When typing |start|(09:00) everything works, when typing |start|(9:00 PM) it doesn't work. Apparently the button creates the wrong text sometimes (maybe because of the locale/timezone of the users browser)?

**Comment by frcroth** [comment]
Yes, you are right. Opened #359
