### ISSUE TITLE
Fresh install not possible

### ISSUE THREAD

**Issue by frcroth** [fsr-de/myHPI#145]
The current wagtail_markdown package depends on markdown.utils.etree, which was already deprecated and removed in version 3.4 of markdown (https://github.com/Python-Markdown/markdown/commit/a767b2daaad78ba32d45a4f1dabb7c5e218f030a). A quick fix would be to set the version of markdown to 3.3.7.

Is this adressed by #116 @jeriox ?

**Comment by jeriox** [comment]
currently not, as I removed markdown completely as a dependency as it is included via wagtail_markdown

**Comment by frcroth** [comment]
Yes but it seems wagtail_markdown still uses the dependency

**Comment by jeriox** [comment]
just commented the problem on the issue there. we can pin the markdown version in the meantime as you suggested
