### ISSUE TITLE
Minutes without moderators

### ISSUE THREAD

**Issue by frcroth** [fsr-de/myHPI#178]
In 1327 there are a lot of minutes (literally hundreds) without moderators. For importing currently I create a Dummy User and make it moderator. Obviously that's not nice. So I think the moderator should be an optional field.

There are also some minutes without author.

**Comment by jeriox** [comment]
Not sure if I like that, as we are requried to note the moderator of a FSR-Sitzung. Having support by the tool to not forget that would be good.

Are those minutes very old? Maybe they are still a bit broken from the import into 1327 from the previous system
