### ISSUE TITLE
Project name

### ISSUE THREAD

**Issue by frcroth** [fsr-de/myHPI#192]

**Comment by SilvanVerhoeven** [comment]
2HPI (German pronounciation. Awesome pun with "myHPI" and "version 2")

**Comment by frcroth** [comment]
> 2HPI (German pronounciation. Awesome pun with "myHPI" and "version 2")

In that case I would prefer the written out version "zweiHPI"

**Comment by frcroth** [comment]
kallaklind (Estonian platypus according to Gtranslate)

**Comment by SilvanVerhoeven** [comment]
Just to make it clear for everyone: Is the "project name" how we name this repo/code base? Like 1327 was the CMS, but myHPI was the website?
