### ISSUE TITLE
Allow Ranking of poll options 

### ISSUE THREAD

**Issue by frcroth** [fsr-de/myHPI#220]

**Comment by frcroth** [comment]
@BenBals wants to tackle this

**Comment by BenBals** [comment]
For ranked choice voting, I need to store a ballot as ranked list of some of the choices. How would I best store that in the model? Have a new `Vote` class which belongs to a user and a poll and stores the ranked choices as an array?

**Comment by frcroth** [comment]
I think a vote could be a json (https://docs.djangoproject.com/en/4.1/ref/models/fields/#jsonfield). This would simplify the model. The JSON could then be the array of choices (or choice ids)

**Comment by BenBals** [comment]
That would mean that the list of choices cannot be changed after voting has started since that would lead to inconsistencies, but I think that would be fine given the application.

**Comment by BenBals** [comment]
Do we want to keep support for first past the post voting?

**Comment by BenBals** [comment]
In order to use JSONFields we need to enable a sqlite extension. Do we have access to that?

https://docs.djangoproject.com/en/4.1/ref/databases/#sqlite-json1

**Comment by BenBals** [comment]
What would be the process for including a javascript library, specifically [sortable.js](http://sortablejs.github.io/Sortable/)? @jeriox @SilvanVerhoeven
