### ISSUE TITLE
Replace ModelChoiceFields with select2 fields

### ISSUE THREAD

**Issue by jeriox** [fsr-de/myHPI#26]
We are using a ManyToManyFields on our pages, e.g. for the participants in minutes. This is rendered as a plain HTML multiselect by wagtail when editing the page:
![grafik](https://user-images.githubusercontent.com/12702135/172329857-0246f1f2-8ce5-495e-b5b3-e3e1202f4492.png)
As the production instance will have around 1000 users (all students), selecting the correct participants will be a huge pain.
1327 is using [select2](https://select2.org/) via https://django-select2.readthedocs.io/en/latest/ for such cases, which renders a single textbox where one can search for the person in question: 
![grafik](https://user-images.githubusercontent.com/12702135/172330348-30584cdb-a9a5-44bd-b04e-5bc8f8c5203f.png)
![grafik](https://user-images.githubusercontent.com/12702135/172330380-7c7810da-cad6-4be2-b131-fd309707d906.png)
We should replace the wagtail panels for these ManyToManyFields with select2 fields or a similar option.

**Comment by frcroth** [comment]
Can you expand on this? Which fields, where and why?

**Comment by jeriox** [comment]
description updated

**Comment by frcroth** [comment]
Could also be implemented with https://github.com/wagtail/wagtail-autocomplete

**Comment by jeriox** [comment]
> Could also be implemented with https://github.com/wagtail/wagtail-autocomplete

I also stumbled upon that some time ago, but the readme says that this only works for choosing pages and being able to choose other models is tbd
