### ISSUE TITLE
Wagtail Admin has links to localhost

### ISSUE THREAD

**Issue by phSch08** [fsr-de/myHPI#269]
In the admin interface there are some references to localhost. The most prominent can be seen in the headline:
![grafik](https://user-images.githubusercontent.com/15707663/216981991-15c58a15-7f1e-4a37-933e-7dd1a561abe5.png)

When editing a page, the preview ("Vorschau") button links to localhost as well.

**Comment by frcroth** [comment]
This is not a bug in myhpi but a problem in the deployment, since this can be edited.
![image](https://user-images.githubusercontent.com/6863832/216983296-a1059599-b1f7-4ca3-b4be-3292ee001f86.png)

**Comment by frcroth** [comment]
![image](https://user-images.githubusercontent.com/6863832/216983476-64f42d0a-733c-4e54-86e7-49398f28d744.png)
