### ISSUE TITLE
Uploading profile picture fails with 413 Request Entity Too Large

### ISSUE THREAD

**Issue by phSch08** [fsr-de/myHPI#270]
While trying to upload a profile picture, I'm getting a "413 Request Entity Too Large" error:
![grafik](https://user-images.githubusercontent.com/15707663/216982891-a813bffe-2b44-4a95-9b4f-1b113b40875f.png)
The picture is a .jpg file and has a size of 10.1 MB.

**Comment by frcroth** [comment]
Uploading profile pictures is currently not supported. You can use gravatar with your hpi address if you want a profile picture, but it wouldn't be used anywhere but the admin user list.

**Comment by frcroth** [comment]
Closed in favor of #271
