### ISSUE TITLE
Last edited by uses UTC

### ISSUE THREAD

**Issue by frcroth** [fsr-de/myHPI#322]
Should use users' local time

![image](https://user-images.githubusercontent.com/6863832/230714943-af0f2f97-d5c8-44e8-912f-257e5bcaa1cd.png)
![image](https://user-images.githubusercontent.com/6863832/230714954-1b2348b3-f2d5-4a66-add9-892df84fb69c.png)

**Comment by Paula-Kli** [comment]
Note: maybe problem on server or client side - a bug in the system that needs to be found
