### ISSUE TITLE
Search in Protocols

### ISSUE THREAD

**Issue by dasGoogle** [fsr-de/myHPI#324]
In the old myHPI, I liked the feature to search through protocols, i.e., of the FSR to look up certain topics. 

![Search in the old myHPI](https://user-images.githubusercontent.com/16378455/230740363-0267ac54-18ed-465c-beef-07583a845077.png)

The new myHPI appears to only search through pages and not protocols, or at least I cannot find such a feature. 
I would love if this feature could be re-added.

**Comment by frcroth** [comment]
Now deployed.
