### ISSUE TITLE
Support multiple anonymous IP ranges

### ISSUE THREAD

**Issue by frcroth** [fsr-de/myHPI#331]

**Comment by jeriox** [comment]
do we actually need this feature? AFAIK we only ever used one group for the university network

**Comment by frcroth** [comment]
Not multiple groups but multiple ip ranges. 1327 had 4.

**Comment by dasGoogle** [comment]
IPv4? IPv6?

**Comment by lukasrad02** [comment]
> IPv4? IPv6?

For the moment, IPv4 should suffice, as our server is not reachable vie IPv6 at all...
