### ISSUE TITLE
Use better widget for minutes guests in wagtail admin 

### ISSUE THREAD

**Issue by jeriox** [fsr-de/myHPI#332]
Currently, the guest field on minutes is using a simple textarea as a widget which displays a JSON array of strings representing the guests. There should be an easy to use widget, like in 1327 with a "add more guests" button. IMO we already implemented this here, maybe it broke somewhere along the way

**Comment by frcroth** [comment]
No it was never implemented, see https://github.com/fsr-de/myHPI/pull/177

**Comment by jeriox** [comment]
ah, then I probably mixed that up with the poll choices where we implemented smth like that ^^
