### ISSUE TITLE
Use select2 widget for author and moderator of minutes

### ISSUE THREAD

**Issue by jeriox** [fsr-de/myHPI#336]
Currently, you need to search in the simple select widget in a list of a few thousand people that aren't sorted alphabetically. We should use a select2 widget with a search function instead.

**Comment by Paula-Kli** [comment]
Sounds like a convenient idea. Just so you know, select2 or therefore our widget to select the participants in minutes is the issue for not updating wagtail 3 to wagtail 4 🙈 . Do you think that there might be another option to build that feature?

**Comment by jeriox** [comment]
oh shit. What's the issue there? select2 is essential, if that doesn't work we need to find a suitable alternative

**Comment by Paula-Kli** [comment]
Here (https://github.com/fsr-de/myHPI/pull/233) you can find a screenshot. Last time I checked the issue remained which is why I never merged those wagtail updates from dependabot.

**Comment by frcroth** [comment]
Maybe consider tomselect: https://tom-select.js.org/
It is also used in EvaP: https://github.com/e-valuation/EvaP/issues/1672
