### ISSUE TITLE
Preview broken

### ISSUE THREAD

**Issue by jeriox** [fsr-de/myHPI#340]
When clicking the "Preview" button in the editor or in the page revisions, a redirect to the currently published version of the page is happening. Instead, the preview should be displayed.

**Comment by jeriox** [comment]
@frcroth for me this works fine locally. Could you test that as well? The URL exists in production as well, but for whatever reason issues the redirect described above

**Comment by lukasrad02** [comment]
Fixed by setting the port of the page to 443 in the deployment as suggested at https://github.com/wagtail/wagtail/issues/5737
