### ISSUE TITLE
Feature Request: Make it easier to search for protocols

### ISSUE THREAD

**Issue by LinqLover** [fsr-de/myHPI#345]
Not sure whether this is a technical or organizational issue, but currently it is rather hard to search the protocols for specific terms because the search results seem to mix up younger and older results: https://myhpi.de/de/search/?query=professur

An option to search in specific folders or to order results by date descending/ascending would be great, but it would already be a help if each protocol item in the search restuls was displayed with a date.

**Comment by frcroth** [comment]
Related to #399

**Comment by jeriox** [comment]
fixed in #577
