### ISSUE TITLE
Usernames are truncated on signing in via OIDC

### ISSUE THREAD

**Issue by frcroth** [fsr-de/myHPI#366]
It seems that the maximum length of a user name created via OIDC is 20 characters (?). This results in some duplicate users, as 1327 did not have this limitation.

**Comment by lukasrad02** [comment]
This is a limitation of the HPI OIDC provider, which truncates the sub at 20 characters. 1327 seems to have derived the username from the email address, which is not truncated.

We've migrated to Keycloak – which uses UUIDs as subs – in the meantime. I've cleaned up duplicate users manually in our production system, there should be no need to change something in the myHPI source code.
