### ISSUE TITLE
Print last commit hash on page

### ISSUE THREAD

**Issue by frcroth** [fsr-de/myHPI#400]
For debugging, it would be nice to see what build is used in the running deployment, which may be printed somewhere on the page.

**Comment by jeriox** [comment]
in my other project we are using https://github.com/mtkennerly/poetry-dynamic-versioning that takes care of building the package with a version derived from the git tag or else the commit hash if none present. Accessing the version is then only a thing of `importlib_metadata.version("package_name")`

**Comment by gh-adithya** [comment]
Hi! I would like to work on this issue as my first contribution. Can I go ahead?
