### ISSUE TITLE
Support dots in commands

### ISSUE THREAD

**Issue by SilvanVerhoeven** [fsr-de/myHPI#42]
The enter and leave commands break if writing names with dots, e.g. "Prof. Friedrich". Just support all characters except "(" and ")".

**Comment by frcroth** [comment]
Is this issue relevant for the new myhpi?

**Comment by jeriox** [comment]
yes, we reused the markdown utilities from 1327

**Comment by frcroth** [comment]
Ok then I don't understand the issue. What are the enter and leave commands and how do they break?
