### ISSUE TITLE
Center images that do not fill the whole page width

### ISSUE THREAD

**Issue by abc013** [fsr-de/myHPI#466]
Title gives it away. This:
![image](https://github.com/fsr-de/myHPI/assets/21260178/56bb36e4-bdc8-4374-aa28-a035426ef8ba)

Should be this IMO:
![image](https://github.com/fsr-de/myHPI/assets/21260178/bcb242cc-ac74-4db1-9190-ed45a32ca82b)

**Comment by frcroth** [comment]
Related to #483

**Comment by jeriox** [comment]
I would also vote against that change

**Comment by abc013** [comment]
On further discussion, seems like I am the only one proposing this change. Closing.
