### ISSUE TITLE
Image Chooser shouldn't display preview

### ISSUE THREAD

**Issue by T4rikA** [fsr-de/myHPI#5]
Currently if you insert an image, the image is displayed in a preview size.
This should be changed to display a higher resolution (800px is generated from wagtail).

Use a regex to find the higher resolution path from the preview path

**Comment by frcroth** [comment]
Maybe generally rethink image support for the editor.

**Comment by lukasrad02** [comment]
It seems like translations are still using smaller images. For example, see

- <https://myhpi.de/de/informationen/ausleihe-fahrradanhaenger/> (DE)
- <https://myhpi.de/en/information/bicycle-trailer-rental/> (EN)

(login required for both pages)
