### ISSUE TITLE
Sidebar should not display empty fields

### ISSUE THREAD

**Issue by jeriox** [fsr-de/myHPI#506]
![grafik](https://github.com/fsr-de/myHPI/assets/12702135/e5b96664-c9ba-4073-b58f-84a18076211c)

**Comment by frcroth** [comment]
What is this specifically about? Only about the visibility field or about the "by" without name, or also about when it displays "No guests" on minutes?

**Comment by jeriox** [comment]
According to @abc013 the "by" issue should be fixed by #383.
This issue was about the empty boxes for visibility and ToC
