### ISSUE TITLE
Icons for external links are misplaced if anchor tag contains additional markup

### ISSUE THREAD

**Issue by lukasrad02** [fsr-de/myHPI#516]
When an anchor tag of an external link contains additional markup (e.g., `<strong>` or `<abbr>` tags), the external link icon will be placed in front of the first inner tag. Therefore, it is sometimes not in the end of the link text.

### Expected behavior: All external links should look like this:
![Screenshot of an external link with icon correctly placed at the end of the text](https://github.com/fsr-de/myHPI/assets/49586507/fee63e47-d3bf-4587-bfbb-64f6067c555f)

### Actual behavior: The icon is in weird positions for some links
In the middle of the link text due to the bold text
![Screenshot of an external link with icon wrongly placed in the middle of the text because the text behind is bold](https://github.com/fsr-de/myHPI/assets/49586507/98f98094-cd6d-421d-97d2-5247fd43740b)

In front of the text due to the abbreviation
![Screenshot of an external link with icon wrongly placed at the beginning of the text because the text starts with a known abbreviation](https://github.com/fsr-de/myHPI/assets/49586507/04504487-cfef-4f2c-a0d1-19da22e4b6a5)

**Comment by dasGoogle** [comment]
As this is an issue that concerns the fact that it is literally impossible to parse HTML via a RegEx, what is the desired solution here? Do we try a best-effort approach that works for basic formatting or do we indeed add a complete HTML parser (I don't think we want to do that)?

**Comment by lukasrad02** [comment]
In my opinion, covering the base cases should be sufficient
