### ISSUE TITLE
Store user language preference

### ISSUE THREAD

**Issue by frcroth** [fsr-de/myHPI#559]
I use an English system language but prefer myHPI in German. I would like to not have to switch to German everytime I visit the page.

E.g. the language preference could be stored in my browser.

**Comment by jeriox** [comment]
Django supports using a cookie for that: https://docs.djangoproject.com/en/5.0/topics/i18n/translation/#how-django-discovers-language-preference

**Comment by frcroth** [comment]
At what point do we need cookie banners?

**Comment by jeriox** [comment]
AFAIK not as long as we only store functional cookies that are required for the basic functionality of the site (e.g. we already store the session id as a cookie, otherwise you would be unable to login)
