### ISSUE TITLE
Attachments are missing in mobile view

### ISSUE THREAD

**Issue by jeriox** [fsr-de/myHPI#606]
![Screenshot_20240808-192747.png](https://github.com/user-attachments/assets/0205aec4-83fe-4a25-9f3c-0c0b45095cae)

![Screenshot_20240808-192738.png](https://github.com/user-attachments/assets/20d8ad8b-84fd-4628-89d7-9adbae7d875d)

**Comment by SilvanVerhoeven** [comment]
They are in the table of content

**Comment by jeriox** [comment]
I think I'd prefer having the attachements down with the rest of the meta information, as this seems the more natural place to look for them (at least for me)
