### ISSUE TITLE
Bootstrap in the repo

### ISSUE THREAD

**Issue by frcroth** [fsr-de/myHPI#67]
I think it is not optimal that bootstrap is included in the repo (https://github.com/fsr-de/myHPI/tree/main/myhpi/static/scss/bootstrap), since it now makes up the majority of the codebase. 

It would be better to make this a dependency or automate the installation in some other way.

![image](https://user-images.githubusercontent.com/6863832/171921172-d2951f66-2d88-485a-b4fa-05c288aabedc.png)

**Comment by jeriox** [comment]
The problem is that there is no easy way (that I know of) to include recent bootstrap versions via pip. Making it a dependency would require another package manager (e.g. 1327 additionally used yarn for frontend assets). I don't really like that

**Comment by frcroth** [comment]
I was thinking more like a shell script

**Comment by jeriox** [comment]
not a big fan of that as well, as this e.g. won't work on windows

**Comment by frcroth** [comment]
Ok, if multi platform support is needed, a python script could be used `install.py`
