### ISSUE TITLE
Can't create minutes list

### ISSUE THREAD

**Issue by frcroth** [fsr-de/myHPI#77]
I can't create a minutes list. 

![image](https://user-images.githubusercontent.com/6863832/172320324-fbfd5233-4604-4e1a-8c32-3dd01269b46c.png)

I'm not entirely sure why and at some point I could create a minute list, since I already have one.

**Comment by jeriox** [comment]
I think this wasn't a multiselect before as you may only choose one group. maybe this is the problem
