### ISSUE TITLE
Convenience functions when creating minutes

### ISSUE THREAD

**Issue by jeriox** [fsr-de/myHPI#78]
There are several small things in 1327 that make taking minutes easier:

- [ ] #99
- [x] The minutes title defaults to the title of the last minutes
- [x] The date defaults to today
- [x] The author and chair default to the values from the last minutes
- [x] The participants default to all members of the respective group
- [x] The URL/slug defaults to the current date

These would also be handy for us.

**Comment by frcroth** [comment]
- A shortcut in the upper right menu to create a minutes (rather than navigating to wagtail-admin and the correct position in the tree) --> I think this should be a separate issue

What exactly are the last minutes? The last minute in this minutes list by date?
