### ISSUE TITLE
Allow polls to be created

### ISSUE THREAD

**Issue by jeriox** [fsr-de/myHPI#79]
As of #23, there is functionality for polls in myHPI. Our current tree configuration does not allow for polls/poll lists to be created anywhere. This should be changed accordingly.

**Comment by jeriox** [comment]
oh, then my local setup may be broken, as it was created before polls were possible. This is my selection when creating a subpage of a root page
![grafik](https://user-images.githubusercontent.com/12702135/172723746-de6c5f2e-792d-403a-bc23-8f6b32041bdb.png)

**Comment by jeriox** [comment]
yeah flushing the database solved the issue.

**Comment by frcroth** [comment]
I am actually now having this problem to. I created a new root page (Page 3) and can not create a poll list.
When I visit http://127.0.0.1:8000/admin/pages/add/polls/polllist/3/ which I used previously to create a poll list, I get this error, even though I am an admin.
![Uploading image.png…]()
