### ISSUE TITLE
Redesign minutes list

### ISSUE THREAD

**Issue by jeriox** [fsr-de/myHPI#87]
The minutes list is currently ugly with only bullet points. We'd like to have a column-based design similar to 1327 which also shows the labels of the minutes and visibility in a nice way
![grafik](https://user-images.githubusercontent.com/12702135/173084498-9afe9350-be8c-4a21-b284-bdf0ee3058ff.png)

**Comment by frcroth** [comment]
Not sure how to implement the visibility. All groups could be listed, but there are no associated icons with groups.

**Comment by jeriox** [comment]
In 1327, these are just hardcoded. A "person" icon is rendered if the minutes is visible for "student". 
On the other hand: the benefit for normal user isn't really there. They aren't interested in who can view the minutes, just that they can view it. It is mainly a reminder for the FSR(-Vorsitz) to quickly see which minutes aren't published. Maybe we could change that to display some kind of warning (exclamation mark?) on unpublished minutes
