### ISSUE TITLE
Page creator should not own page

### ISSUE THREAD

**Issue by frcroth** [fsr-de/myHPI#89]
Currently the page creator will always have the rights to the created page, it is not possible to revoke these rights. This can be problematic, since permissions are not static (FSRs change..)

Possible approaches:
- Create a dummy user, all pages will be created by that user (use some hook)
- Do not give the creator immediate rights to a page as default in wagtail

**Comment by jeriox** [comment]
The owner can also be null on the page model, so clearing the owner works as well

**Comment by frcroth** [comment]
Works for me already. Steps to test:

1. Create a test user
2. Add that test user to the "Student representative group" and "Student representatives" groups
3. Allow "student representative group" group access to wagtail admin, give page permissions to some page for this group
4. Allow "student representatives" group access to wagtail admin
5. In another browser: sign in as test user
6. As test user create a new page
7. In your first browser, remove test user from "Student representative group" (thus removing edit right to the page)
8. In your second browser, validate that you can no longer edit the page test user created.

**Comment by frcroth** [comment]
This would be the fix if it were a problem. In myhpi/core/wagtail_hooks.py
```
@hooks.register("after_create_page")
def do_after_page_creation(request, page):
    page.owner_id = None
    new_revision = page.save_revision()
    if page.live:
        new_revision.publish()
```
