### ISSUE TITLE
Minutes list shows unpublished entries

### ISSUE THREAD

**Issue by frcroth** [fsr-de/myHPI#92]
Minutes list does not check if minutes are published or not.

**Comment by jeriox** [comment]
Maybe we should also filter the displayed minutes by whether the current user is allowed to view them

**Comment by frcroth** [comment]
Yes, of course, though this would need to wait for #57, when utilities are added to determine which pages can be viewed. I would not implement this here because of code duplication.

**Comment by jeriox** [comment]
If the user has edit permissions/can add minutes, the list should also display unpublished minutes

**Comment by frcroth** [comment]
@Paula-Kli Sorry, I already handled this in #93, it seemed natural to solve these two issues at once.
