### ISSUE TITLE
Menu shortcut for minutes creation

### ISSUE THREAD

**Issue by jeriox** [fsr-de/myHPI#99]
A shortcut in the upper right menu to create a minutes (rather than navigating to wagtail-admin and the correct position in the tree)

**Comment by frcroth** [comment]
How does the button now where to put the created minutes?

**Comment by jeriox** [comment]
My proposal would be to iterate over all groups that the current user belongs to. For each group, we can find the minutes list that belongs to the group via the reverse accessor. We can then check whether the user has the permission to create a subpage for that page. If that is the case, we can remember the ID of that page and render a button labeled with the corresponding group.

**Comment by jeriox** [comment]
waiting for #31 as the top menu isn't there yet
